import { notFound } from "next/navigation";
import Link from "next/link";
import type { Metadata } from "next";
import { db } from "@/lib/db";
import { Badge, toneForKind, toneForSeverity } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Logo } from "@/components/marketing/logo";

interface PageProps {
  params: Promise<{ id: string }>;
}

interface StoredFinding {
  providerSlug: string;
  providerName: string;
  title: string;
  kind: string;
  severity: string;
  summary: string | null;
  effectiveAt: string | null;
  url: string | null;
}

function isStoredFinding(value: unknown): value is StoredFinding {
  return (
    typeof value === "object" &&
    value !== null &&
    "providerName" in value &&
    "title" in value &&
    "severity" in value
  );
}

export const metadata: Metadata = {
  title: "Stack impact report",
  description:
    "A dependency impact report: recent breaking changes, deprecations, and incidents across this stack, generated by Upstream.",
  robots: { index: false }, // shared reports are for humans, not crawlers
};

/**
 * Public shareable impact report — the viral unit. A developer runs a report,
 * shares the link in Slack/a PR/a post-mortem, and every reader sees a
 * concrete, useful artifact with a one-click path to running their own.
 * Attribution footer is on by default; hiding it is the Pro perk.
 */
export default async function PublicReportPage({ params }: PageProps) {
  const { id } = await params;
  const report = await db.impactReport.findUnique({
    where: { publicId: id },
    include: { user: { select: { referralCode: true } } },
  });
  if (report === null) notFound();

  const rawFindings: unknown = report.findings;
  const findings = Array.isArray(rawFindings)
    ? rawFindings.filter(isStoredFinding)
    : [];
  const refLink = `/?ref=${report.user.referralCode}`;

  return (
    <div className="min-h-screen bg-ink-950">
      <header className="border-b border-line">
        <div className="mx-auto flex h-14 max-w-3xl items-center justify-between px-6">
          <Link href="/" aria-label="Upstream home">
            <Logo />
          </Link>
          <span className="datum text-xs text-fg-faint">
            impact report · {report.createdAt.toISOString().slice(0, 10)}
          </span>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-12">
        <h1 className="font-display text-2xl font-semibold text-fg">
          Stack impact report
        </h1>
        <p className="mt-2 text-sm text-fg-muted">
          {report.matchedProviders.length} providers matched from this stack's
          dependencies · {findings.length} findings in the last 90 days.
        </p>

        <div className="mt-4 flex flex-wrap gap-2">
          {report.matchedProviders.map((slug) => (
            <Link key={slug} href={`/p/${slug}`}>
              <Badge tone="pulse" className="cursor-pointer transition-colors hover:border-pulse/50">
                {slug}
              </Badge>
            </Link>
          ))}
        </div>

        <div className="mt-8 space-y-3">
          {findings.length === 0 ? (
            <div className="rounded-xl border border-signal/25 bg-signal-faint p-8 text-center">
              <p className="font-display text-base font-semibold text-fg">
                All clear — no high-impact changes in the last 90 days.
              </p>
              <p className="mt-1 text-sm text-fg-muted">
                The useful part is staying this way. Watching this stack takes
                one click.
              </p>
            </div>
          ) : (
            findings.map((finding, index) => (
              <article
                key={`${finding.providerSlug}-${index}`}
                className="rounded-xl border border-line bg-ink-900 p-4 etch"
              >
                <div className="flex flex-wrap items-center gap-2">
                  <span className="datum text-xs font-medium text-fg-muted">
                    {finding.providerName}
                  </span>
                  <Badge tone={toneForKind(finding.kind)}>{finding.kind}</Badge>
                  <Badge tone={toneForSeverity(finding.severity)}>{finding.severity}</Badge>
                  {finding.effectiveAt !== null ? (
                    <span className="datum ml-auto text-xs text-ember">
                      deadline {finding.effectiveAt.slice(0, 10)}
                    </span>
                  ) : null}
                </div>
                <h2 className="mt-2 font-display text-sm font-semibold text-fg">
                  {finding.url !== null ? (
                    <a
                      href={finding.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="transition-colors hover:text-signal"
                    >
                      {finding.title}
                    </a>
                  ) : (
                    finding.title
                  )}
                </h2>
                {finding.summary !== null ? (
                  <p className="mt-1.5 text-sm text-fg-muted">{finding.summary}</p>
                ) : null}
              </article>
            ))
          )}
        </div>

        <div className="mt-12 rounded-xl border border-line bg-ink-900 p-6 text-center etch">
          <h2 className="font-display text-lg font-semibold text-fg">
            Run this on your own package.json
          </h2>
          <p className="mx-auto mt-1 max-w-sm text-sm text-fg-muted">
            Paste your manifest, get your stack's last 90 days of breakage in
            ten seconds. Free, no card.
          </p>
          <Link href={refLink} className="mt-4 inline-block">
            <Button>Check my stack</Button>
          </Link>
        </div>

        {report.attributionShown ? (
          <p className="mt-8 text-center">
            <Link
              href={refLink}
              className="datum text-xs text-fg-faint transition-colors hover:text-fg-muted"
            >
              Watched by Upstream — know before it breaks
            </Link>
          </p>
        ) : null}
      </main>
    </div>
  );
}
